#!/usr/bin/env bash
set -ex

pip install --no-cache-dir "dynamic-foraging-processing[full] @ git+https://github.com/AllenNeuralDynamics/dynamic-foraging-processing.git@8515a8f8858df5da5dd13c0445db3c70b4319191"

pip install -U --no-cache-dir "boto3"