#!/usr/bin/env bash
set -ex

pip install --no-cache-dir "dynamic-foraging-processing[full] @ git+https://github.com/AllenNeuralDynamics/dynamic-foraging-processing.git@ad9d1c872d2f0732de8dc4b5189fdfdb3e8b8ad9"

pip install -U --no-cache-dir "boto3"