#!/usr/bin/env bash
set -ex

pip install --no-cache-dir "dynamic-foraging-processing[full] @ git+https://github.com/AllenNeuralDynamics/dynamic-foraging-processing.git@v0.1.0"

pip install -U --no-cache-dir "boto3"